sudo: false
language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
matrix:
  include:
    - rvm: 2.5
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.5
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.6
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.7
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.7
      gemfile: gemfiles/rails_6.0.gemfile