version: '3'

services:
  rails:
    build: .
    volumes:
      - bundle_cache:/bundle
      - .:/app
    environment:
      - BUNDLE_JOBS=5
      - BUNDLE_PATH=/bundle
      - BUNDLE_BIN=/bundle/bin
      - GEM_HOME=/bundle
      - DOCKER_CONTAINER=1
    command:
      - docker/start.sh

volumes:
  bundle_cache:
